[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
PORT = 5000